name = "Tutorials"
uuid = "a23be9e4-3fb3-4e3f-bb56-e0ed2f5b57c7"
authors = ["SciQuant"]
version = "0.1.0"

[deps]
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
UniversalDynamics = "e34ebe0d-adf9-4359-84c2-dfdf884d416d"

[compat]
Literate = "2.8"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
